<script setup lang="ts">
import { computed,nextTick,onBeforeUnmount,onMounted,ref,watch } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import { ElMessage,ElMessageBox } from 'element-plus'
import ScientificText from '../../components/question/ScientificText.vue'
import AnswerDisplay from '../../components/question/AnswerDisplay.vue'
import QuestionContent from '../../components/question/QuestionContent.vue'
import StandardAnalysis from '../../components/question/StandardAnalysis.vue'
import { questionTypeLabel } from '../../utils/questionLabels'
import { fetchStudentPaper,fetchStudentPapers,saveStudentPaperDraft,submitStudentPaper,type StudentPaperDetail,type StudentPaperRelease } from '../../api/student/papers'

const route=useRoute(),router=useRouter(),papers=ref<StudentPaperRelease[]>([]),detail=ref<StudentPaperDetail>(),answers=ref<Record<number,unknown>>({}),saving=ref(false),submitting=ref(false),missingItems=ref<Set<number>>(new Set())
const releaseId=computed(()=>Number(route.params.releaseId||0))
let saveTimer:number|undefined
let savePromise:Promise<void>|undefined,missingTimer:number|undefined
const objectiveTypes=new Set(['SINGLE_CHOICE','MULTIPLE_CHOICE','FILL_BLANK'])
function initialAnswer(question:StudentPaperDetail['questions'][number]){if(question.submittedAnswer!==null&&question.submittedAnswer!==undefined)return question.submittedAnswer;if(question.type==='MULTIPLE_CHOICE')return [];if(question.type==='FILL_BLANK')return Array.from({length:question.answerSlots},()=> '');return ''}
async function load(){window.clearTimeout(saveTimer);papers.value=await fetchStudentPapers();if(releaseId.value){detail.value=await fetchStudentPaper(releaseId.value);answers.value=Object.fromEntries(detail.value.questions.map(q=>[q.itemId,initialAnswer(q)]))}}
function answerIsComplete(question:StudentPaperDetail['questions'][number]){const answer=answers.value[question.itemId];if(question.type==='SINGLE_CHOICE')return typeof answer==='string'&&answer.trim().length>0;if(question.type==='MULTIPLE_CHOICE')return Array.isArray(answer)&&answer.some(value=>typeof value==='string'&&value.trim().length>0);if(question.type==='FILL_BLANK')return Array.isArray(answer)&&answer.length===question.answerSlots&&answer.every(value=>typeof value==='string'&&value.trim().length>0);return true}
function answerChanged(itemId:number){if(missingItems.value.has(itemId)){const next=new Set(missingItems.value);next.delete(itemId);missingItems.value=next}scheduleSave()}
function fill(itemId:number,index:number,value:string){const current=Array.isArray(answers.value[itemId])?[...(answers.value[itemId] as string[])]:[];current[index]=value;answers.value[itemId]=current;answerChanged(itemId)}
function scheduleSave(){if(detail.value?.answersVisible||submitting.value)return;window.clearTimeout(saveTimer);saveTimer=window.setTimeout(()=>void saveDraft(),700)}
async function saveDraft(){if(!releaseId.value||detail.value?.answersVisible||submitting.value)return;if(savePromise)await savePromise;if(detail.value?.answersVisible||submitting.value)return;saving.value=true;const request=saveStudentPaperDraft(releaseId.value,payload()).catch((error:any)=>{ElMessage.warning(error.message||'草稿自动保存失败，请检查网络后重试')}).finally(()=>{saving.value=false;savePromise=undefined});savePromise=request;await request}
function payload(){return detail.value?.questions.map(question=>({itemId:question.itemId,answer:answers.value[question.itemId]}))??[]}
async function validateBeforeSubmit(){const missing=(detail.value?.questions??[]).filter(question=>objectiveTypes.has(question.type)&&!answerIsComplete(question));if(!missing.length)return true;missingItems.value=new Set(missing.map(question=>question.itemId));window.clearTimeout(missingTimer);missingTimer=window.setTimeout(()=>{missingItems.value=new Set()},2600);ElMessage.warning(`还有 ${missing.length} 道客观题未完成：第${missing.map(question=>question.order).join('、')}题。`);await nextTick();document.querySelector(`[data-item-id="${missing[0].itemId}"]`)?.scrollIntoView({behavior:'smooth',block:'center'});return false}
function submitErrorMessage(error:any){return ({PAPER_ANSWER_INCOMPLETE:'还有客观题未完成，请检查后重新提交',PAPER_CLOSED:'试卷已截止，不能继续提交',PAPER_ALREADY_SUBMITTED:'该试卷已经提交，请刷新查看结果',PAPER_ITEM_FORBIDDEN:'当前答案与发布试卷不一致，请刷新后重新进入'} as Record<string,string>)[error?.code]||error?.message||'试卷提交失败，请稍后重试'}
async function submit(){if(!(await validateBeforeSubmit()))return;try{await ElMessageBox.confirm('提交后不能修改客观题答案；主观题将保存并等待教师处理。','确认提交试卷',{confirmButtonText:'确认提交',cancelButtonText:'继续检查'})}catch(error){if(error==='cancel'||error==='close')return;ElMessage.error('无法打开提交确认，请稍后重试');return}submitting.value=true;window.clearTimeout(saveTimer);try{if(savePromise)await savePromise;const result=await submitStudentPaper(releaseId.value,payload());ElMessage.success(`提交成功：客观题自动得分 ${result.objectiveScore}/${result.objectiveTotal}${result.subjectivePendingCount ? `；${result.subjectivePendingCount} 道主观题待教师处理` : ''}`);await load()}catch(error:any){ElMessage.error(submitErrorMessage(error))}finally{submitting.value=false}}
watch(releaseId,load);onMounted(load);onBeforeUnmount(()=>{window.clearTimeout(saveTimer);window.clearTimeout(missingTimer)})
</script>
<template><main class="student-papers"><header><div><h1>{{detail?'试卷作答':'我的试卷'}}</h1></div><el-button v-if="detail" @click="router.push('/student/papers')">返回任务列表</el-button></header>
<section v-if="!detail" class="release-grid"><article v-for="paper in papers" :key="paper.id" class="release-card"><div><el-tag>{{paper.subjectName}}</el-tag><el-tag :type="paper.submissionStatus==='SUBMITTED'?'success':'warning'">{{paper.submissionStatus==='SUBMITTED'?'已提交':'待作答'}}</el-tag></div><h2>{{paper.paperName}}</h2><p>{{paper.className}} · 截止 {{new Date(paper.deadline).toLocaleString()}}</p><strong v-if="paper.submissionStatus==='SUBMITTED'">客观题自动得分 {{paper.score}} / {{paper.objectiveTotal}}</strong><el-button type="primary" @click="router.push(`/student/papers/${paper.id}`)">{{paper.submissionStatus==='SUBMITTED'?'查看结果':'开始作答'}}</el-button></article><el-empty v-if="!papers.length" description="当前没有试卷任务"/></section>
<template v-else><section class="paper-meta"><h2>{{detail.release.paperName}}</h2><span>{{detail.release.subjectName}} · {{detail.release.className}}</span><el-tag :type="detail.release.submissionStatus==='SUBMITTED'?'success':'warning'">{{detail.release.submissionStatus==='SUBMITTED'?'已提交':detail.release.submissionStatus==='IN_PROGRESS'?'作答中':'待作答'}}</el-tag><small>{{saving?'草稿保存中…':'草稿自动保存'}}</small></section>
<section class="question-list"><article v-for="question in detail.questions" :key="question.itemId" class="paper-question" :class="{'paper-question--missing':missingItems.has(question.itemId)}" :data-item-id="question.itemId"><div class="question-heading"><strong>{{question.order}}.</strong><el-tag effect="plain">{{questionTypeLabel(question.type)}}</el-tag><span>{{question.score}} 分</span></div><QuestionContent :content="question.stem" :attachments="question.stemAttachments" position="QUESTION"/><el-radio-group v-if="question.type==='SINGLE_CHOICE'" v-model="answers[question.itemId]" :disabled="detail.answersVisible" @change="answerChanged(question.itemId)"><el-radio v-for="option in question.options" :key="option.label" :value="option.label"><b>{{option.label}}.</b> <ScientificText :content="option.content"/></el-radio></el-radio-group><el-checkbox-group v-else-if="question.type==='MULTIPLE_CHOICE'" v-model="answers[question.itemId] as string[]" :disabled="detail.answersVisible" @change="answerChanged(question.itemId)"><el-checkbox v-for="option in question.options" :key="option.label" :value="option.label"><b>{{option.label}}.</b> <ScientificText :content="option.content"/></el-checkbox></el-checkbox-group><div v-else-if="question.type==='FILL_BLANK'" class="blank-list"><el-input v-for="index in question.answerSlots" :key="index" :model-value="(answers[question.itemId] as string[])[index-1]" :disabled="detail.answersVisible" :placeholder="`第 ${index} 空`" @update:model-value="fill(question.itemId,index-1,$event)"/></div><div v-else><el-alert title="主观大题提交后等待教师处理。" type="info" :closable="false"/><el-input type="textarea" :rows="10" placeholder="请分步骤作答；提交后等待教师处理。" :disabled="detail.answersVisible" v-model="answers[question.itemId]" @input="answerChanged(question.itemId)"/></div><section v-if="detail.answersVisible" class="result"><div class="answer-result"><h3>学生答案</h3><AnswerDisplay :value="question.submittedAnswer" :question-type="question.type" :options="question.options"/></div><div class="score-result"><el-tag :type="question.correct===true?'success':question.correct===false?'danger':'info'">{{question.correct===true?'正确':question.correct===false?'错误':'已提交 · 待教师处理'}}</el-tag><strong v-if="objectiveTypes.has(question.type)">本题得分 {{question.awardedScore??0}} / {{question.score}}</strong></div><div v-if="question.correctAnswer" class="answer-result"><h3>正确答案</h3><AnswerDisplay :value="question.correctAnswer" :question-type="question.type" :options="question.options"/></div><div class="standard"><h3>STANDARD</h3><StandardAnalysis :content="question.standardAnalysis||'主观题已提交，等待教师处理。'" :attachments="question.analysisAttachments"/></div></section></article></section><footer v-if="!detail.answersVisible"><span>提交前请检查所有客观题；主观题提交后等待教师处理。</span><el-button type="primary" :loading="submitting" @click="submit">提交试卷</el-button></footer></template></main></template>
<style scoped>.student-papers{max-width:1100px;margin:0 auto;padding:28px}.student-papers>header{display:flex;justify-content:space-between;align-items:end;gap:20px}.student-papers header p{letter-spacing:.12em;color:#477b8c}.student-papers h1{margin:4px 0}.release-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:16px;margin-top:24px}.release-card,.paper-meta,.paper-question{border:1px solid color-mix(in srgb,var(--el-color-primary) 18%,transparent);border-radius:18px;background:var(--el-bg-color);box-shadow:0 12px 34px rgba(32,91,111,.08)}.release-card{display:grid;gap:12px;padding:20px}.release-card>div,.paper-meta{display:flex;gap:10px;align-items:center}.paper-meta{margin:24px 0;padding:18px}.paper-meta small{margin-left:auto;color:var(--el-text-color-secondary)}.question-list{display:grid;gap:18px}.paper-question{padding:22px;transition:border-color .2s ease,box-shadow .2s ease}.paper-question--missing{border-color:var(--el-color-warning);box-shadow:0 0 0 3px var(--el-color-warning-light-8)}.question-heading{display:flex;gap:10px;align-items:center;margin-bottom:12px}.paper-question :deep(.el-radio),.paper-question :deep(.el-checkbox){display:flex;height:auto;margin:10px 0;white-space:normal}.paper-question :deep(.scientific-text){display:inline}.blank-list{display:grid;gap:10px;margin-top:16px}.result{display:grid;gap:14px;margin-top:18px;padding-top:18px;border-top:1px solid var(--el-border-color-lighter)}.answer-result h3{margin:0 0 8px}.score-result{display:flex;align-items:center;gap:12px}.standard{padding:16px;border-radius:14px;background:var(--el-color-primary-light-9)}.student-papers>footer{position:sticky;bottom:12px;display:flex;justify-content:space-between;align-items:center;margin-top:20px;padding:14px 18px;border:1px solid var(--el-border-color);border-radius:16px;background:color-mix(in srgb,var(--el-bg-color) 92%,transparent);backdrop-filter:blur(14px)}@media(max-width:600px){.student-papers{padding:16px}.student-papers>header,.student-papers>footer{align-items:stretch;flex-direction:column}.paper-meta{align-items:flex-start;flex-wrap:wrap}.paper-meta small{width:100%;margin:0}}</style>
