<script setup lang="ts">
import { computed,onMounted,ref,watch } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import { ElMessage,ElMessageBox } from 'element-plus'
import ScientificText from '../../components/question/ScientificText.vue'
import AnswerDisplay from '../../components/question/AnswerDisplay.vue'
import { fetchStudentPaper,fetchStudentPapers,saveStudentPaperDraft,submitStudentPaper,type StudentPaperDetail,type StudentPaperRelease } from '../../api/student/papers'

const route=useRoute(),router=useRouter(),papers=ref<StudentPaperRelease[]>([]),detail=ref<StudentPaperDetail>(),answers=ref<Record<number,unknown>>({}),saving=ref(false),submitting=ref(false)
const releaseId=computed(()=>Number(route.params.releaseId||0))
let saveTimer:number|undefined
async function load(){papers.value=await fetchStudentPapers();if(releaseId.value){detail.value=await fetchStudentPaper(releaseId.value);answers.value=Object.fromEntries(detail.value.questions.filter(q=>q.submittedAnswer!==null).map(q=>[q.itemId,q.submittedAnswer]))}}
function fill(itemId:number,index:number,value:string){const current=Array.isArray(answers.value[itemId])?[...(answers.value[itemId] as string[])]:[];current[index]=value;answers.value[itemId]=current;scheduleSave()}
function scheduleSave(){if(detail.value?.answersVisible)return;window.clearTimeout(saveTimer);saveTimer=window.setTimeout(saveDraft,700)}
async function saveDraft(){if(!releaseId.value||detail.value?.answersVisible)return;saving.value=true;try{await saveStudentPaperDraft(releaseId.value,payload())}finally{saving.value=false}}
function payload(){return Object.entries(answers.value).map(([itemId,answer])=>({itemId:Number(itemId),answer}))}
async function submit(){await ElMessageBox.confirm('提交后将冻结客观题答案，主观题不由 AI 判分。','确认提交试卷',{confirmButtonText:'确认提交',cancelButtonText:'继续检查'});submitting.value=true;try{const result=await submitStudentPaper(releaseId.value,payload());ElMessage.success(`客观题得分 ${result.objectiveScore}/${result.objectiveTotal}`);await load()}finally{submitting.value=false}}
watch(releaseId,load);onMounted(load)
</script>
<template><main class="student-papers"><header><div><p>FROZEN PAPER WORKSPACE</p><h1>{{detail?'试卷作答':'我的试卷'}}</h1><span>发布后题干、选项、分值与 STANDARD 均被冻结；客观题由确定性规则判分。</span></div><el-button v-if="detail" @click="router.push('/student/papers')">返回任务列表</el-button></header>
<section v-if="!detail" class="release-grid"><article v-for="paper in papers" :key="paper.id" class="release-card"><div><el-tag>{{paper.subjectName}}</el-tag><el-tag :type="paper.submissionStatus==='SUBMITTED'?'success':'warning'">{{paper.submissionStatus}}</el-tag></div><h2>{{paper.paperName}}</h2><p>{{paper.className}} · 截止 {{new Date(paper.deadline).toLocaleString()}}</p><strong v-if="paper.submissionStatus==='SUBMITTED'">{{paper.score}} / {{paper.objectiveTotal}}</strong><el-button type="primary" @click="router.push(`/student/papers/${paper.id}`)">{{paper.submissionStatus==='SUBMITTED'?'查看结果':'开始作答'}}</el-button></article><el-empty v-if="!papers.length" description="当前没有试卷任务"/></section>
<template v-else><section class="paper-meta"><h2>{{detail.release.paperName}}</h2><span>{{detail.release.subjectName}} · {{detail.release.className}}</span><el-tag>{{detail.release.submissionStatus}}</el-tag><small>{{saving?'草稿保存中…':'草稿自动保存'}}</small></section>
<section class="question-list"><article v-for="question in detail.questions" :key="question.itemId" class="paper-question"><div class="question-heading"><strong>{{question.order}}.</strong><el-tag effect="plain">{{question.type}}</el-tag><span>{{question.score}} 分</span></div><ScientificText :content="question.stem"/><el-radio-group v-if="question.type==='SINGLE_CHOICE'" v-model="answers[question.itemId]" :disabled="detail.answersVisible" @change="scheduleSave"><el-radio v-for="option in question.options" :key="option.label" :value="option.label"><b>{{option.label}}.</b> <ScientificText :content="option.content"/></el-radio></el-radio-group><el-checkbox-group v-else-if="question.type==='MULTIPLE_CHOICE'" v-model="answers[question.itemId] as string[]" :disabled="detail.answersVisible" @change="scheduleSave"><el-checkbox v-for="option in question.options" :key="option.label" :value="option.label"><b>{{option.label}}.</b> <ScientificText :content="option.content"/></el-checkbox></el-checkbox-group><div v-else-if="question.type==='FILL_BLANK'" class="blank-list"><el-input v-for="index in question.answerSlots" :key="index" :model-value="(answers[question.itemId] as string[]||[])[index-1]" :disabled="detail.answersVisible" :placeholder="`第 ${index} 空`" @update:model-value="fill(question.itemId,index-1,$event)"/></div><el-input v-else type="textarea" :rows="6" placeholder="主观草稿仅保存在本次试卷提交中，不自动评分" :disabled="detail.answersVisible" v-model="answers[question.itemId]" @input="scheduleSave"/><section v-if="detail.answersVisible" class="result"><el-tag :type="question.correct===true?'success':question.correct===false?'danger':'info'">{{question.correct===true?'正确':question.correct===false?'错误':'待教师处理'}}</el-tag><AnswerDisplay v-if="question.correctAnswer" :value="question.correctAnswer" :question-type="question.type" :options="question.options"/><div class="standard"><h3>STANDARD</h3><ScientificText :content="question.standardAnalysis||'主观题等待教师处理'"/></div></section></article></section><footer v-if="!detail.answersVisible"><span>提交前请检查所有客观题；主观题不会由 AI 自动评分。</span><el-button type="primary" :loading="submitting" @click="submit">提交试卷</el-button></footer></template></main></template>
<style scoped>.student-papers{max-width:1100px;margin:0 auto;padding:28px}.student-papers>header{display:flex;justify-content:space-between;align-items:end;gap:20px}.student-papers header p{letter-spacing:.12em;color:#477b8c}.student-papers h1{margin:4px 0}.release-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:16px;margin-top:24px}.release-card,.paper-meta,.paper-question{border:1px solid color-mix(in srgb,var(--el-color-primary) 18%,transparent);border-radius:18px;background:var(--el-bg-color);box-shadow:0 12px 34px rgba(32,91,111,.08)}.release-card{display:grid;gap:12px;padding:20px}.release-card>div,.paper-meta{display:flex;gap:10px;align-items:center}.paper-meta{margin:24px 0;padding:18px}.paper-meta small{margin-left:auto;color:var(--el-text-color-secondary)}.question-list{display:grid;gap:18px}.paper-question{padding:22px}.question-heading{display:flex;gap:10px;align-items:center;margin-bottom:12px}.paper-question :deep(.el-radio),.paper-question :deep(.el-checkbox){display:flex;height:auto;margin:10px 0;white-space:normal}.paper-question :deep(.scientific-text){display:inline}.blank-list{display:grid;gap:10px;margin-top:16px}.result{display:grid;gap:14px;margin-top:18px;padding-top:18px;border-top:1px solid var(--el-border-color-lighter)}.standard{padding:16px;border-radius:14px;background:var(--el-color-primary-light-9)}.student-papers>footer{position:sticky;bottom:12px;display:flex;justify-content:space-between;align-items:center;margin-top:20px;padding:14px 18px;border:1px solid var(--el-border-color);border-radius:16px;background:color-mix(in srgb,var(--el-bg-color) 92%,transparent);backdrop-filter:blur(14px)}@media(max-width:600px){.student-papers{padding:16px}.student-papers>header,.student-papers>footer{align-items:stretch;flex-direction:column}.paper-meta{align-items:flex-start;flex-wrap:wrap}.paper-meta small{width:100%;margin:0}}</style>
