<script setup lang="ts">
import {computed,onMounted,reactive,ref} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {ElMessage} from 'element-plus'
import {fetchTeacherWorkspace} from '../../api/teacher'
import {createKnowledgeCard,fetchTeacherKnowledgeCards,reviewKnowledgeCard,uploadKnowledgeCardImage,type KnowledgeCardSave} from '../../api/teacher/knowledgeCards'
import type {KnowledgeCard} from '../../api/student/knowledgeCards'
import ScientificText from '../../components/question/ScientificText.vue'
const route=useRoute(),router=useRouter(),scopeId=computed(()=>Number(route.params.scopeId)),cards=ref<KnowledgeCard[]>([]),points=ref<Array<{id:number;path:string}>>([]),loading=ref(false),saving=ref(false),image=ref<File>(),created=ref<KnowledgeCard>()
const types=[['POINT','考点'],['FORMULA','公式'],['CHEMICAL_EQUATION','方程式'],['SECONDARY_CONCLUSION','二级结论'],['INSTRUMENT','实验器具'],['MNEMONIC','口诀'],['TABLE','表格'],['NOTE','笔记']]
const form=reactive<KnowledgeCardSave>({type:'POINT',title:'',knowledgePointIds:[],content:'',latex:'',applicableConditions:'',derivation:'',commonMistake:'',example:'',mnemonic:'',sourceName:'项目自编总结',sourceUrl:'',rightsStatus:'PROJECT_AUTHORED',sortOrder:1,aiDraft:false})
async function load(){loading.value=true;try{const [workspace,list]=await Promise.all([fetchTeacherWorkspace(scopeId.value),fetchTeacherKnowledgeCards(scopeId.value)]);points.value=workspace.knowledgePoints;cards.value=list}catch{ElMessage.error('知识卡片工作台加载失败。')}finally{loading.value=false}}
async function save(){if(!form.title.trim()||!form.content.trim()||!form.knowledgePointIds.length)return ElMessage.warning('请填写标题、正文并选择知识点。');saving.value=true;try{created.value=await createKnowledgeCard(scopeId.value,{...form});if(image.value)await uploadKnowledgeCardImage(created.value.id,image.value);ElMessage.success(form.aiDraft?'AI 整理草稿已进入 PENDING，需人工审核。':'项目自编卡片已发布到本任课范围。');Object.assign(form,{title:'',knowledgePointIds:[],content:'',latex:'',applicableConditions:'',derivation:'',commonMistake:'',example:'',mnemonic:'',sortOrder:1,aiDraft:false});image.value=undefined;await load()}catch{ElMessage.error('知识卡片保存失败。')}finally{saving.value=false}}
async function review(card:KnowledgeCard,action:'APPROVE'|'REJECT'|'DISABLE'){try{await reviewKnowledgeCard(card.id,action,action==='APPROVE'?'教师核验内容与来源后通过':'教师人工处理');await load()}catch{ElMessage.error('审核状态更新失败。')}}
function selectFile(event:Event){image.value=(event.target as HTMLInputElement).files?.[0]}
onMounted(load)
</script>
<template><main class="teacher-cards"><header><div><p>TEACHER REVIEW WORKFLOW</p><h1>知识卡片与公式口诀</h1><span>复用高频考点模块；AI 整理内容必须 PENDING，人工核验后才对本班学生可见。</span></div><el-button @click="router.push(`/teacher/scopes/${scopeId}`)">返回工作台</el-button></header><section class="editor"><h2>新增卡片</h2><div class="grid"><label>类型<el-select v-model="form.type"><el-option v-for="t in types" :key="t[0]" :label="t[1]" :value="t[0]"/></el-select></label><label>标题<el-input v-model="form.title" maxlength="200"/></label><label>知识点<el-select v-model="form.knowledgePointIds" multiple filterable><el-option v-for="p in points" :key="p.id" :label="p.path" :value="p.id"/></el-select></label><label>排序<el-input-number v-model="form.sortOrder" :min="0"/></label></div><label>科学正文<el-input v-model="form.content" type="textarea" :rows="4"/></label><div class="grid"><label>LaTeX<el-input v-model="form.latex"/></label><label>适用条件<el-input v-model="form.applicableConditions"/></label><label>含义 / 推导<el-input v-model="form.derivation"/></label><label>常见误区<el-input v-model="form.commonMistake"/></label><label>简单例子<el-input v-model="form.example"/></label><label>记忆口诀<el-input v-model="form.mnemonic"/></label><label>来源名称<el-input v-model="form.sourceName"/></label><label>来源链接<el-input v-model="form.sourceUrl"/></label><label>权利状态<el-select v-model="form.rightsStatus"><el-option label="项目自编" value="PROJECT_AUTHORED"/><el-option label="公共领域" value="PUBLIC_DOMAIN"/><el-option label="已授权" value="AUTHORIZED"/><el-option label="用户提供" value="USER_PROVIDED"/></el-select></label><label>可选图片（PNG/JPEG）<input type="file" accept="image/png,image/jpeg" @change="selectFile"></label></div><el-checkbox v-model="form.aiDraft">这是 AI 整理草稿（保存为 PENDING）</el-checkbox><el-button type="primary" :loading="saving" @click="save">保存卡片</el-button></section><section v-loading="loading" class="cards"><article v-for="card in cards" :key="card.id"><div><el-tag>{{types.find(t=>t[0]===card.type)?.[1]}}</el-tag><el-tag :type="card.status==='PUBLISHED'?'success':card.status==='PENDING'?'warning':'info'">{{card.status}}</el-tag></div><h2>{{card.title}}</h2><ScientificText :content="card.content"/><small>{{card.knowledgePoints.map(p=>p.path).join(' · ')}}</small><footer><el-button v-if="card.status==='PENDING'" type="success" plain @click="review(card,'APPROVE')">人工审核通过</el-button><el-button v-if="card.status==='PENDING'" @click="review(card,'REJECT')">驳回</el-button><el-button v-if="card.status==='PUBLISHED'" type="warning" plain @click="review(card,'DISABLE')">停用</el-button></footer></article></section></main></template>
<style scoped>.teacher-cards{max-width:1280px;margin:auto;padding:28px}.teacher-cards>header{display:flex;justify-content:space-between;gap:20px}.editor{margin:20px 0;padding:22px;border:1px solid var(--el-border-color-lighter);border-radius:20px;background:white}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.grid label,.editor>label{display:grid;gap:7px;margin-bottom:14px}.cards{display:grid;grid-template-columns:repeat(auto-fill,minmax(290px,1fr));gap:14px}.cards article{padding:18px;border-radius:16px;background:white;border:1px solid var(--el-border-color-lighter)}.cards article>div,.cards footer{display:flex;gap:8px}.cards small{color:var(--el-text-color-secondary)}@media(max-width:640px){.teacher-cards{padding:14px}.grid{grid-template-columns:1fr}}</style>
