// @vitest-environment jsdom
import {flushPromises,mount} from '@vue/test-utils'
import {beforeEach,describe,expect,it,vi} from 'vitest'
import StudentAiVariantPanel from './StudentAiVariantPanel.vue'
const api=vi.hoisted(()=>({generateAiVariant:vi.fn(),answerAiVariant:vi.fn(),discardAiVariant:vi.fn(),submitAiVariantReview:vi.fn()}))
vi.mock('../../api/student/aiLearning',()=>api)
vi.mock('element-plus',()=>({ElMessage:{warning:vi.fn(),info:vi.fn()}}))
const variant={id:8,answerFactId:3,motherQuestionId:1,questionId:9,status:'READY',questionType:'SINGLE_CHOICE',stem:'电场力满足 F=qE',difficulty:2,options:[{label:'A',content:'沿电场方向'},{label:'B',content:'垂直电场'}],reviewStatus:'PENDING'}
const stubs={AiScientificContent:{props:['content'],template:'<div>{{content}}</div>'},AnswerDisplay:{template:'<div>可读答案</div>'},ElButton:{props:['loading','disabled'],template:'<button :disabled="disabled" @click="$emit(\'click\')"><slot/></button>'},ElCheckboxGroup:{template:'<div><slot/></div>'},ElCheckbox:true,ElRadioGroup:{template:'<div><slot/></div>'},ElRadio:{props:['value'],template:'<label><input type="radio" @click="$emit(\'update:modelValue\',value)">{{value}}<slot/></label>'},ElInput:true,ElTag:{template:'<span><slot/></span>'}}
describe('学生 AI 变式练习',()=>{beforeEach(()=>{vi.clearAllMocks();api.generateAiVariant.mockResolvedValue(variant);api.answerAiVariant.mockResolvedValue({...variant,status:'ANSWERED',correct:true,aiAnalysis:'AI 解析',correctAnswer:{optionLabels:['A']}})})
it('展示难度、完整选择项、练习结果和教师审核入口',async()=>{const wrapper=mount(StudentAiVariantPanel,{props:{answerFactId:3},global:{stubs}});expect(wrapper.text()).toContain('保持母题难度');await wrapper.get('button').trigger('click');await flushPromises();expect(wrapper.text()).toContain('A. 沿电场方向');expect(wrapper.text()).toContain('B. 垂直电场');const vm=wrapper.vm as unknown as {single:string};vm.single='A';await wrapper.vm.$nextTick();const submit=wrapper.findAll('button').find(item=>item.text()==='提交答案');await submit!.trigger('click');await flushPromises();expect(wrapper.text()).toContain('回答正确');expect(wrapper.text()).toContain('本次练习解析');expect(wrapper.text()).toContain('提交教师审核');expect(wrapper.text()).not.toContain('PENDING','尚未成为正式 STANDARD')})})
