<script setup lang="ts">
import { computed, ref } from 'vue';import { ElMessage } from 'element-plus';import { answerAiVariant,discardAiVariant,generateAiVariant,submitAiVariantReview,type AiVariant } from '../../api/student/aiLearning';import AiScientificContent from './AiScientificContent.vue'
const props=defineProps<{answerFactId:number}>();const variant=ref<AiVariant>();const loading=ref(false);const single=ref('');const multiple=ref<string[]>([]);const blanks=ref<string[]>(['']);const submitted=computed(()=>variant.value&&variant.value.status!=='READY')
async function generate(){loading.value=true;try{variant.value=await generateAiVariant(props.answerFactId);single.value='';multiple.value=[];blanks.value=['']}catch(e:any){ElMessage.warning(e.message||'生成结果不完整，请换一题')}finally{loading.value=false}}
async function answer(){if(!variant.value)return;const value=variant.value.questionType==='SINGLE_CHOICE'?single.value:variant.value.questionType==='MULTIPLE_CHOICE'?multiple.value:blanks.value;variant.value=await answerAiVariant(variant.value.id,value)}
async function replace(){if(variant.value&&variant.value.status!=='SUBMITTED_FOR_REVIEW')await discardAiVariant(variant.value.id);await generate()}
async function submit(){if(variant.value)variant.value=await submitAiVariantReview(variant.value.id)}
</script>
<template><section class="ai-variant"><header><div><h3>AI 变式练习</h3><p>每次生成 1 道可自动判分候选题；提交后仍需教师或管理员审核。</p></div><el-button type="primary" :loading="loading" @click="variant?replace():generate()">{{variant?'换一题':'生成变式题'}}</el-button></header><article v-if="variant"><AiScientificContent :content="variant.stem"/><el-checkbox-group v-if="variant.questionType==='MULTIPLE_CHOICE'" v-model="multiple" :disabled="submitted"><el-checkbox v-for="option in variant.options" :key="option.label" :value="option.label">{{option.label}}. {{option.content}}</el-checkbox></el-checkbox-group><el-radio-group v-else-if="variant.questionType==='SINGLE_CHOICE'" v-model="single" :disabled="submitted"><el-radio v-for="option in variant.options" :key="option.label" :value="option.label">{{option.label}}. {{option.content}}</el-radio></el-radio-group><div v-else><el-input v-for="(_,index) in blanks" :key="index" v-model="blanks[index]" :disabled="submitted" :placeholder="`第 ${index+1} 空`"/></div><el-button v-if="variant.status==='READY'" type="primary" @click="answer">提交答案</el-button><div v-else class="variant-result"><el-tag :type="variant.correct?'success':'danger'">{{variant.correct?'回答正确':'回答有误'}}</el-tag><h4>AI 生成解析</h4><AiScientificContent :content="variant.aiAnalysis||''"/><el-button v-if="variant.status==='ANSWERED'" @click="submit">提交人工审核</el-button><el-tag v-else>已提交审核 · {{variant.reviewStatus}}</el-tag></div></article></section></template><style scoped>.ai-variant{margin-top:18px;padding:18px;border:1px solid var(--el-border-color);border-radius:16px}.ai-variant header{display:flex;justify-content:space-between;gap:16px}.ai-variant article{display:grid;gap:14px}.ai-variant .el-checkbox-group,.ai-variant .el-radio-group{display:grid;gap:8px}@media(max-width:640px){.ai-variant header{flex-direction:column}}</style>
