<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, type FormInstance, type FormRules } from 'element-plus'
import { type ApiError } from '../../api/http'
import { changeTeachingAssignmentStatus, createTeacher, createTeachingAssignment, fetchSubjects, fetchTeacher, fetchTeachers, type AccountStatus, type SubjectItem, type TeacherDetail, type TeacherItem, type TeacherProfileStatus, type TeachingAssignmentStatus, updateTeacher } from '../../api/admin/teachers'
import { fetchClasses, type ClassItem } from '../../api/admin/classes'

const loading = ref(false); const saving = ref(false); const teacherDialog = ref(false); const detailVisible = ref(false); const assignmentDialog = ref(false)
const editing = ref(false); const formRef = ref<FormInstance>(); const assignmentRef = ref<FormInstance>(); const teachers = ref<TeacherItem[]>([]); const total = ref(0); const detail = ref<TeacherDetail | null>(null); const classes = ref<ClassItem[]>([]); const subjects = ref<SubjectItem[]>([]); const initialPassword = ref<string | null>(null)
const filters = reactive({ employeeNumber: '', name: '', username: '', accountStatus: '' as '' | AccountStatus, profileStatus: '' as '' | TeacherProfileStatus, page: 1, size: 10 })
const form = reactive({ id: 0, employeeNumber: '', name: '', username: '', displayPosition: '', initialPassword: '', accountStatus: 'ENABLED' as AccountStatus, profileStatus: 'ACTIVE' as TeacherProfileStatus })
const assignment = reactive({ classId: undefined as number | undefined, subjectId: undefined as number | undefined, primary: false, startTime: new Date().toISOString().slice(0, 16) })
const accountStatuses: Array<{ label: string; value: AccountStatus }> = [{ label: '启用', value: 'ENABLED' }, { label: '停用', value: 'DISABLED' }, { label: '锁定', value: 'LOCKED' }]
const profileStatuses: Array<{ label: string; value: TeacherProfileStatus }> = [{ label: '有效', value: 'ACTIVE' }, { label: '停用', value: 'DISABLED' }]
const assignmentStatuses: Array<{ label: string; value: TeachingAssignmentStatus }> = [{ label: '任课中', value: 'ACTIVE' }, { label: '已结束', value: 'ENDED' }, { label: '已停用', value: 'DISABLED' }]
const teacherRules: FormRules = { employeeNumber: [{ required: true, message: '请填写工号', trigger: 'blur' }], name: [{ required: true, message: '请填写姓名', trigger: 'blur' }], username: [{ required: true, message: '请填写用户名', trigger: 'blur' }], initialPassword: [{ min: 8, max: 64, message: '初始密码需为8至64位', trigger: 'blur' }] }
const assignmentRules: FormRules = { classId: [{ required: true, message: '请选择班级', trigger: 'change' }], subjectId: [{ required: true, message: '请选择科目', trigger: 'change' }], startTime: [{ required: true, message: '请选择开始时间', trigger: 'change' }] }
function message(error: unknown, fallback: string) { const api = error as ApiError; const map: Record<string, string> = { TEACHER_NUMBER_EXISTS: '工号已存在。', USERNAME_EXISTS: '用户名已存在。', TEACHER_ROLE_UNAVAILABLE: 'TEACHER角色不可用，请联系系统管理员。', TEACHING_ASSIGNMENT_EXISTS: '该教师、班级、科目关系已存在，历史关系不可重复创建。', TEACHER_UNAVAILABLE: '教师账号或档案不是有效状态。', CLASS_UNAVAILABLE: '班级不存在或不是在读状态。', SUBJECT_UNAVAILABLE: '该科目当前不可用于任课关系。', TEACHING_ASSIGNMENT_REACTIVATION_NOT_SUPPORTED: '为保留历史，已结束或停用关系不可重新启用。' }; return api.code ? map[api.code] || api.message || fallback : api.message || fallback }
async function loadTeachers() { loading.value = true; try { const data = await fetchTeachers({ ...filters, employeeNumber: filters.employeeNumber || undefined, name: filters.name || undefined, username: filters.username || undefined, accountStatus: filters.accountStatus || undefined, profileStatus: filters.profileStatus || undefined }); teachers.value = data.records; total.value = data.total } catch (error) { ElMessage.error(message(error, '教师列表加载失败。')) } finally { loading.value = false } }
function resetFilters() { Object.assign(filters, { employeeNumber: '', name: '', username: '', accountStatus: '', profileStatus: '', page: 1 }); void loadTeachers() }
function openCreate() { editing.value = false; Object.assign(form, { id: 0, employeeNumber: '', name: '', username: '', displayPosition: '', initialPassword: '', accountStatus: 'ENABLED', profileStatus: 'ACTIVE' }); teacherDialog.value = true }
async function openEdit(item: TeacherItem) { try { const data = await fetchTeacher(item.id); editing.value = true; Object.assign(form, data.teacher, { initialPassword: '' }); teacherDialog.value = true } catch (error) { ElMessage.error(message(error, '教师详情加载失败。')) } }
async function saveTeacher() { const valid = await formRef.value?.validate().catch(() => false); if (!valid) return; saving.value = true; try { if (editing.value) await updateTeacher(form.id, { name: form.name.trim(), displayPosition: form.displayPosition.trim() || undefined, accountStatus: form.accountStatus, profileStatus: form.profileStatus }); else { const result = await createTeacher({ employeeNumber: form.employeeNumber.trim(), name: form.name.trim(), username: form.username.trim(), displayPosition: form.displayPosition.trim() || undefined, initialPassword: form.initialPassword || undefined, accountStatus: form.accountStatus }); initialPassword.value = result.initialPassword } ElMessage.success(editing.value ? '教师信息已保存。' : '教师账号已创建，初始密码仅显示本次。'); teacherDialog.value = false; await loadTeachers() } catch (error) { ElMessage.error(message(error, '教师保存失败。')) } finally { saving.value = false } }
async function showDetail(item: TeacherItem) { try { detail.value = await fetchTeacher(item.id); detailVisible.value = true } catch (error) { ElMessage.error(message(error, '教师详情加载失败。')) } }
async function openAssignment() { if (!detail.value) return; try { const [classPage, subjectData] = await Promise.all([fetchClasses({ page: 1, size: 100, status: 'ACTIVE' }), fetchSubjects()]); classes.value = classPage.records; subjects.value = subjectData; Object.assign(assignment, { classId: undefined, subjectId: undefined, primary: false, startTime: new Date().toISOString().slice(0, 16) }); assignmentDialog.value = true } catch (error) { ElMessage.error(message(error, '班级或科目数据加载失败。')) } }
async function saveAssignment() { const valid = await assignmentRef.value?.validate().catch(() => false); if (!valid || !detail.value || assignment.classId === undefined || assignment.subjectId === undefined) return; saving.value = true; try { await createTeachingAssignment(detail.value.teacher.id, { classId: assignment.classId, subjectId: assignment.subjectId, primary: assignment.primary, startTime: new Date(assignment.startTime).toISOString() }); detail.value = await fetchTeacher(detail.value.teacher.id); assignmentDialog.value = false; ElMessage.success('任课关系已创建。') } catch (error) { ElMessage.error(message(error, '任课关系创建失败。')) } finally { saving.value = false } }
async function updateAssignmentStatus(id: number, status: TeachingAssignmentStatus) { try { await changeTeachingAssignmentStatus(id, status); if (detail.value) detail.value = await fetchTeacher(detail.value.teacher.id); ElMessage.success('任课关系状态已更新。') } catch (error) { ElMessage.error(message(error, '任课关系状态更新失败。')) } }
function clearInitialPassword() { initialPassword.value = null; ElMessage.success('一次性初始密码已从当前页面清除。') }
function label(options: Array<{ label: string; value: string }>, value: string) { return options.find(item => item.value === value)?.label || value }
onMounted(loadTeachers)
</script>

<template>
  <section class="admin-page">
    <div class="page-heading"><div><h1>教师与任课关系</h1><p>管理员创建教师账号，并以教师、班级、科目三元关系授予后续数据范围。</p></div><el-button type="primary" @click="openCreate">创建教师</el-button></div>
    <el-alert v-if="initialPassword" class="inline-alert" type="warning" :closable="false" show-icon><template #title>初始密码仅显示一次：<strong>{{ initialPassword }}</strong><el-button link type="danger" @click="clearInitialPassword">立即清空</el-button></template></el-alert>
    <el-form class="filter-panel" :inline="true" @submit.prevent="filters.page = 1; loadTeachers()"><el-form-item label="工号"><el-input v-model="filters.employeeNumber" clearable /></el-form-item><el-form-item label="姓名"><el-input v-model="filters.name" clearable /></el-form-item><el-form-item label="用户名"><el-input v-model="filters.username" clearable /></el-form-item><el-form-item label="账号"><el-select v-model="filters.accountStatus" clearable><el-option v-for="item in accountStatuses" :key="item.value" :label="item.label" :value="item.value" /></el-select></el-form-item><el-form-item label="档案"><el-select v-model="filters.profileStatus" clearable><el-option v-for="item in profileStatuses" :key="item.value" :label="item.label" :value="item.value" /></el-select></el-form-item><el-form-item><el-button type="primary" native-type="submit">查询</el-button><el-button @click="resetFilters">重置</el-button><el-button :loading="loading" @click="loadTeachers">刷新</el-button></el-form-item></el-form>
    <el-table v-loading="loading" :data="teachers" class="data-table" empty-text="暂无教师数据，可先创建教师账号。"><el-table-column prop="employeeNumber" label="工号" min-width="130" /><el-table-column prop="name" label="姓名" min-width="110" /><el-table-column prop="username" label="用户名" min-width="130" /><el-table-column prop="displayPosition" label="展示职务" min-width="140" /><el-table-column label="账号状态" min-width="110"><template #default="{ row }"><el-tag :type="row.accountStatus === 'ENABLED' ? 'success' : 'danger'">{{ label(accountStatuses, row.accountStatus) }}</el-tag></template></el-table-column><el-table-column label="档案状态" min-width="110"><template #default="{ row }"><el-tag :type="row.profileStatus === 'ACTIVE' ? 'success' : 'info'">{{ label(profileStatuses, row.profileStatus) }}</el-tag></template></el-table-column><el-table-column label="操作" fixed="right" min-width="150"><template #default="{ row }"><el-button link type="primary" @click="showDetail(row)">详情与任课</el-button><el-button link type="primary" @click="openEdit(row)">编辑</el-button></template></el-table-column></el-table>
    <el-pagination class="table-pagination" background layout="total, sizes, prev, pager, next" :total="total" v-model:current-page="filters.page" v-model:page-size="filters.size" :page-sizes="[10, 20, 50]" @current-change="loadTeachers" @size-change="filters.page = 1; loadTeachers()" />
    <el-dialog v-model="teacherDialog" :title="editing ? '编辑教师' : '创建教师'" width="min(560px, calc(100vw - 32px))" destroy-on-close><el-form ref="formRef" :model="form" :rules="teacherRules" label-width="96px"><el-form-item label="工号" prop="employeeNumber"><el-input v-model="form.employeeNumber" :disabled="editing" /></el-form-item><el-form-item label="姓名" prop="name"><el-input v-model="form.name" /></el-form-item><el-form-item label="用户名" prop="username"><el-input v-model="form.username" :disabled="editing" /></el-form-item><el-form-item label="展示职务"><el-input v-model="form.displayPosition" /></el-form-item><el-form-item v-if="!editing" label="初始密码" prop="initialPassword"><el-input v-model="form.initialPassword" type="password" show-password placeholder="不填则生成随机密码" /></el-form-item><el-form-item label="账号状态"><el-select v-model="form.accountStatus"><el-option v-for="item in accountStatuses" :key="item.value" :label="item.label" :value="item.value" /></el-select></el-form-item><el-form-item v-if="editing" label="档案状态"><el-select v-model="form.profileStatus"><el-option v-for="item in profileStatuses" :key="item.value" :label="item.label" :value="item.value" /></el-select></el-form-item></el-form><template #footer><el-button @click="teacherDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="saveTeacher">保存</el-button></template></el-dialog>
    <el-drawer v-model="detailVisible" title="教师详情与任课关系" size="min(860px, 100%)"><template v-if="detail"><div class="teacher-detail"><el-descriptions :column="2" border><el-descriptions-item label="工号">{{ detail.teacher.employeeNumber }}</el-descriptions-item><el-descriptions-item label="姓名">{{ detail.teacher.name }}</el-descriptions-item><el-descriptions-item label="用户名">{{ detail.teacher.username }}</el-descriptions-item><el-descriptions-item label="有效角色">{{ detail.roles.join('、') || '无' }}</el-descriptions-item><el-descriptions-item label="展示职务">{{ detail.teacher.displayPosition || '—' }}</el-descriptions-item><el-descriptions-item label="账号 / 档案">{{ label(accountStatuses, detail.teacher.accountStatus) }} / {{ label(profileStatuses, detail.teacher.profileStatus) }}</el-descriptions-item></el-descriptions><div class="section-title-row teacher-assignment-heading"><div><h2>任课关系</h2><p>结束或停用后保留原记录，不提供物理删除。</p></div><el-button type="primary" @click="openAssignment">添加任课关系</el-button></div><el-table :data="detail.teachingAssignments" class="data-table" empty-text="暂无任课关系。"><el-table-column prop="classCode" label="班级编码" min-width="110" /><el-table-column prop="className" label="班级" min-width="130" /><el-table-column prop="subjectName" label="科目" min-width="100" /><el-table-column label="主任课" min-width="90"><template #default="{row}">{{ row.primary ? '是' : '否' }}</template></el-table-column><el-table-column label="状态" min-width="110"><template #default="{row}"><el-tag :type="row.status === 'ACTIVE' ? 'success' : 'info'">{{ label(assignmentStatuses,row.status) }}</el-tag></template></el-table-column><el-table-column prop="startTime" label="开始时间" min-width="170" /><el-table-column prop="endTime" label="结束时间" min-width="170" /><el-table-column label="操作" min-width="130"><template #default="{row}"><el-dropdown @command="(status: TeachingAssignmentStatus) => updateAssignmentStatus(row.id,status)"><el-button link type="primary">变更状态</el-button><template #dropdown><el-dropdown-menu><el-dropdown-item v-for="item in assignmentStatuses" :key="item.value" :command="item.value" :disabled="item.value===row.status">{{ item.label }}</el-dropdown-item></el-dropdown-menu></template></el-dropdown></template></el-table-column></el-table></div></template></el-drawer>
    <el-dialog v-model="assignmentDialog" title="添加三元任课关系" width="min(520px, calc(100vw - 32px))" destroy-on-close><el-alert type="info" :closable="false" title="班级与科目均来自后端真实数据；相同教师、班级、科目不可重复创建。" /><el-form ref="assignmentRef" :model="assignment" :rules="assignmentRules" label-width="92px" style="margin-top:20px"><el-form-item label="班级" prop="classId"><el-select v-model="assignment.classId" filterable style="width:100%"><el-option v-for="item in classes" :key="item.id" :label="`${item.className}（${item.classCode}）`" :value="item.id" /></el-select></el-form-item><el-form-item label="科目" prop="subjectId"><el-select v-model="assignment.subjectId" style="width:100%"><el-option v-for="item in subjects" :key="item.id" :label="item.subjectName" :value="item.id" /></el-select></el-form-item><el-form-item label="主任课"><el-switch v-model="assignment.primary" /></el-form-item><el-form-item label="开始时间" prop="startTime"><el-date-picker v-model="assignment.startTime" type="datetime" value-format="YYYY-MM-DDTHH:mm" style="width:100%" /></el-form-item></el-form><template #footer><el-button @click="assignmentDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="saveAssignment">创建关系</el-button></template></el-dialog>
  </section>
</template>
