<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import type { AiCandidate, AiGenerationClient, AiGenerationStats, AiGenerationTask, MotherOption, ReviewRequest } from '../../api/aiGeneration'
import type { ApiError } from '../../api/http'

const props=defineProps<{mode:'ADMIN'|'TEACHER';client:AiGenerationClient}>()
const isAdmin=computed(()=>props.mode==='ADMIN')
const mothers=ref<MotherOption[]>([]);const tasks=ref<AiGenerationTask[]>([]);const points=ref<Array<{id:number;name:string;path:string}>>([]);const stats=ref<AiGenerationStats>();const loading=ref(false);const generating=ref(false)
const detailVisible=ref(false);const selected=ref<AiCandidate>();const reviewing=ref(false)
const form=reactive({motherQuestionId:undefined as number|undefined,questionType:'SINGLE_CHOICE',knowledgePointIds:[] as number[],targetDifficulty:2,variationMode:'NUMERIC_CONDITION',count:1})
const review=reactive<ReviewRequest>({subjectCorrectness:1,answerCorrectness:1,solvability:1,knowledgeConsistency:1,difficultyMatch:1,reviewResult:'APPROVED',reviewMinutes:5,reviewComment:''})
const selectedMother=computed(()=>mothers.value.find(item=>item.id===form.motherQuestionId))
const errorText=(error:unknown,fallback:string)=>(error as ApiError).message||fallback
const label=(value:string)=>({SINGLE_CHOICE:'单选题',MULTIPLE_CHOICE:'多选题',FILL_BLANK:'填空题',NUMERIC_CONDITION:'数值条件变化',SCENARIO:'情境变化',KNOWLEDGE_ANGLE:'知识角度变化',DISTRACTOR:'干扰项变化',COMBINED:'组合变化',SUCCESS:'生成成功',FAILED:'生成失败',GENERATING:'生成中',PENDING:'待审核',PUBLISHED:'已发布',DRAFT:'已退回'} as Record<string,string>)[value]||value
async function load(){loading.value=true;try{const [motherData,taskData,statsData]=await Promise.all([props.client.fetchMothers(),props.client.fetchTasks(),props.client.fetchStats?.()]);mothers.value=motherData;tasks.value=taskData;stats.value=statsData}catch(e){ElMessage.error(errorText(e,'AI 候选题数据加载失败。'))}finally{loading.value=false}}
async function changeMother(){const mother=selectedMother.value;form.knowledgePointIds=[];if(!mother){points.value=[];return}form.questionType=mother.questionType==='FILL_BLANK'?'FILL_BLANK':'SINGLE_CHOICE';form.targetDifficulty=Math.min(5,Math.max(1,mother.difficulty));try{points.value=await props.client.fetchKnowledgePoints(mother.subjectId)}catch(e){ElMessage.error(errorText(e,'知识点加载失败。'))}}
async function generate(){if(!form.motherQuestionId||!form.knowledgePointIds.length){ElMessage.warning('请选择母题和至少一个知识点。');return}generating.value=true;try{await props.client.createTask({...form,motherQuestionId:form.motherQuestionId});ElMessage.success('候选题已生成并进入 PENDING 人工审核。');await load()}catch(e){ElMessage.error(errorText(e,'候选题生成失败，未创建正式题目。'))}finally{generating.value=false}}
function openCandidate(candidate:AiCandidate){selected.value=candidate;Object.assign(review,{subjectCorrectness:1,answerCorrectness:1,solvability:1,knowledgeConsistency:1,difficultyMatch:1,reviewResult:'APPROVED',reviewMinutes:5,reviewComment:''});detailVisible.value=true}
async function submitReview(){if(!selected.value)return;if(review.reviewResult==='REJECTED'&&!review.reviewComment?.trim()){ElMessage.warning('驳回必须填写审核意见。');return}reviewing.value=true;try{selected.value=await props.client.reviewCandidate(selected.value.questionId,{...review});ElMessage.success(review.reviewResult==='APPROVED'?'人工审核通过，题目已发布。':'候选题已驳回并保留评价记录。');await load();detailVisible.value=false}catch(e){ElMessage.error(errorText(e,'质量评价提交失败。'))}finally{reviewing.value=false}}
onMounted(load)
defineExpose({form,review,changeMother,generate,openCandidate,submitReview})
</script>

<template>
  <section class="admin-page generation-page" v-loading="loading" :data-workspace-mode="mode">
    <div class="page-heading"><div><span class="page-kicker">AI CANDIDATE WORKFLOW</span><h1>AI 变式题生成与审核</h1><p>{{ isAdmin?'查看全局生成事实、重复提示与人工质量审核。':'仅展示本人任教学科的已发布母题与候选任务。' }} 所有结果只进入 PENDING，必须人工评价后发布。</p></div><el-button :loading="loading" @click="load">刷新</el-button></div>
    <div v-if="isAdmin&&stats" class="generation-metrics"><article><span>生成任务</span><strong>{{ stats.tasks }}</strong></article><article><span>候选题</span><strong>{{ stats.generated }}</strong></article><article><span>重复提示</span><strong>{{ stats.suspectedDuplicates }}</strong></article><article><span>审核通过 / 驳回</span><strong>{{ stats.approved }} / {{ stats.rejected }}</strong></article></div>
    <section class="generation-form-panel">
      <div class="section-title-row"><div><h2>创建生成任务</h2><p>单次 1～3 道；同一母题最多保留 6 道 PENDING 候选。</p></div><el-tag effect="plain">只选择 PUBLISHED 母题</el-tag></div>
      <el-form label-position="top" @submit.prevent="generate">
        <div class="generation-form-grid">
          <el-form-item label="母题" class="mother-field"><el-select v-model="form.motherQuestionId" filterable placeholder="按题干选择已发布母题" @change="changeMother"><el-option v-for="item in mothers" :key="item.id" :label="`#${item.id} · ${item.subjectCode} · ${item.stem}`" :value="item.id" /></el-select></el-form-item>
          <el-form-item label="目标题型"><el-select v-model="form.questionType"><el-option label="单选题" value="SINGLE_CHOICE" /><el-option label="多选题" value="MULTIPLE_CHOICE" /><el-option label="填空题" value="FILL_BLANK" /></el-select></el-form-item>
          <el-form-item label="知识点"><el-select v-model="form.knowledgePointIds" multiple filterable><el-option v-for="item in points" :key="item.id" :label="item.path" :value="item.id" /></el-select></el-form-item>
          <el-form-item label="目标难度"><el-select v-model="form.targetDifficulty"><el-option v-for="value in 5" :key="value" :label="`${value} 级`" :value="value" /></el-select></el-form-item>
          <el-form-item label="变化方式"><el-select v-model="form.variationMode"><el-option v-for="value in ['NUMERIC_CONDITION','SCENARIO','KNOWLEDGE_ANGLE','DISTRACTOR','COMBINED']" :key="value" :label="label(value)" :value="value" /></el-select></el-form-item>
          <el-form-item label="生成数量"><el-input-number v-model="form.count" :min="1" :max="3" /></el-form-item>
        </div>
        <div v-if="selectedMother" class="mother-preview"><span>当前绑定母题</span><strong>#{{ selectedMother.id }} · {{ selectedMother.subjectCode }} · {{ label(selectedMother.questionType) }}</strong><p>{{ selectedMother.stem }}</p></div>
        <el-button type="primary" native-type="submit" :loading="generating">生成候选题</el-button>
      </el-form>
    </section>
    <section class="generation-list"><div class="section-title-row"><div><h2>生成与审核记录</h2><p>Provider 与模型仅在授权审核工作区显示；学生端不会获得这些元数据。</p></div></div><el-empty v-if="!tasks.length" description="尚无 AI 候选生成任务。" />
      <article v-for="task in tasks" v-else :key="task.id" class="generation-task-card"><header><div><el-tag :type="task.status==='SUCCESS'?'success':task.status==='FAILED'?'danger':'warning'">{{ label(task.status) }}</el-tag><strong>任务 #{{ task.id }} · 母题 #{{ task.motherQuestionId }}</strong><span>{{ label(task.questionType) }} · 难度 {{ task.targetDifficulty }} · {{ label(task.variationMode) }}</span></div><div class="task-meta"><span>{{ task.provider || '—' }} / {{ task.model || '—' }}</span><span>{{ task.latencyMillis ?? '—' }} ms · {{ task.generatedCount }}/{{ task.requestedCount }} 道</span></div></header><el-alert v-if="task.status==='FAILED'" :title="`生成失败：${task.failureCode || '受控失败'}`" type="error" :closable="false" /><div v-if="task.candidates.length" class="candidate-grid"><button v-for="candidate in task.candidates" :key="candidate.questionId" type="button" class="candidate-card" @click="openCandidate(candidate)"><span><el-tag size="small">{{ label(candidate.status) }}</el-tag><el-tag v-if="candidate.noveltyDecision==='ACCEPT'" size="small" type="success">新颖度通过</el-tag><el-tag v-else-if="candidate.noveltyDecision==='WARN'" size="small" type="warning">新颖度提示</el-tag><el-tag v-if="candidate.duplicateWarning==='SUSPECTED_DUPLICATE'" size="small" type="warning">疑似相似</el-tag><el-tag v-if="candidate.visionUsed" size="small" type="info">使用视觉</el-tag></span><strong>#{{ candidate.questionId }} · {{ candidate.stem }}</strong><small>{{ candidate.variationSummary }}</small></button></div></article>
    </section>
    <el-drawer v-model="detailVisible" title="AI 候选题人工审核" size="min(760px, 100%)"><template v-if="selected"><el-alert title="候选内容不是系统 STANDARD；只有本次人工审核通过后才发布。" type="warning" :closable="false" show-icon /><div class="candidate-detail"><div><span>题干</span><p>{{ selected.stem }}</p></div><div><span>变式说明</span><p>{{ selected.variationSummary }}</p></div><div><span>候选答案</span><AnswerDisplay :question-type="selected.questionType" :value="selected.correctAnswer" :options="selected.options" /><details><summary>技术结构</summary><pre>{{ selected.correctAnswer }}</pre></details></div><div><span>候选解析</span><p>{{ selected.standardAnalysis }}</p></div><div><span>知识点</span><p>{{ selected.knowledgePoints.map(item=>item.name).join('；') }}</p></div><div><span>生成事实</span><p>{{ selected.provider }} / {{ selected.model }} · {{ selected.visionUsed?'已使用视觉上下文':'纯文本母题' }} · {{ selected.duplicateWarning }}</p></div></div><el-divider content-position="left">质量评价</el-divider><el-form label-position="top"><div class="quality-grid"><el-form-item v-for="field in [{key:'subjectCorrectness',name:'学科正确性'},{key:'answerCorrectness',name:'答案正确性'},{key:'solvability',name:'可解性'},{key:'knowledgeConsistency',name:'知识一致性'},{key:'difficultyMatch',name:'难度匹配'}]" :key="field.key" :label="field.name"><el-radio-group v-model="(review as any)[field.key]"><el-radio-button :value="1">通过</el-radio-button><el-radio-button :value="0">不通过</el-radio-button></el-radio-group></el-form-item></div><el-form-item label="审核结果"><el-radio-group v-model="review.reviewResult"><el-radio value="APPROVED">通过并发布</el-radio><el-radio value="REJECTED">驳回保留记录</el-radio></el-radio-group></el-form-item><el-form-item label="审核耗时（分钟）"><el-input-number v-model="review.reviewMinutes" :min="0" :max="10080" /></el-form-item><el-form-item label="审核意见"><el-input v-model="review.reviewComment" type="textarea" :rows="3" maxlength="2000" show-word-limit /></el-form-item></el-form><div class="drawer-actions"><el-button @click="detailVisible=false">取消</el-button><el-button :type="review.reviewResult==='APPROVED'?'success':'danger'" :loading="reviewing" @click="submitReview">提交人工评价</el-button></div></template></el-drawer>
  </section>
</template>

<style scoped>
.generation-metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:20px}.generation-metrics article,.generation-form-panel,.generation-task-card{border:1px solid var(--color-border,#dce7f1);border-radius:16px;background:#fff;box-shadow:0 10px 28px rgba(42,69,97,.06)}.generation-metrics article{padding:18px}.generation-metrics span{display:block;color:var(--el-text-color-secondary);font-size:12px}.generation-metrics strong{display:block;margin-top:8px;color:#214363;font-size:25px}.generation-form-panel{padding:24px;margin-bottom:26px}.generation-form-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:0 16px}.generation-form-grid .mother-field{grid-column:span 2}.generation-form-grid :deep(.el-select){width:100%}.mother-preview{margin:-4px 0 18px;padding:14px 16px;border-left:3px solid var(--el-color-primary);border-radius:8px;background:var(--el-fill-color-light)}.mother-preview span,.candidate-detail span{color:var(--el-text-color-secondary);font-size:12px}.mother-preview strong{display:block;margin:4px 0}.mother-preview p{margin:0;line-height:1.6}.generation-task-card{padding:20px;margin-bottom:14px}.generation-task-card header{display:flex;justify-content:space-between;gap:18px;margin-bottom:14px}.generation-task-card header>div:first-child{display:flex;align-items:center;flex-wrap:wrap;gap:10px}.generation-task-card header span,.task-meta{color:var(--el-text-color-secondary);font-size:12px}.task-meta{display:flex;align-items:flex-end;flex-direction:column;gap:5px}.candidate-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.candidate-card{display:flex;min-height:130px;flex-direction:column;gap:9px;padding:15px;text-align:left;border:1px solid var(--el-border-color-light);border-radius:12px;background:var(--el-fill-color-blank);cursor:pointer}.candidate-card:hover,.candidate-card:focus-visible{border-color:var(--el-color-primary);box-shadow:0 8px 20px rgba(42,112,176,.1);outline:none}.candidate-card strong{line-height:1.55}.candidate-card small{color:var(--el-text-color-secondary);line-height:1.5}.candidate-card>span{display:flex;gap:5px;flex-wrap:wrap}.candidate-detail{display:grid;gap:14px;margin:18px 0}.candidate-detail>div{padding:14px;border-radius:10px;background:var(--el-fill-color-light)}.candidate-detail p,.candidate-detail pre{margin:5px 0 0;white-space:pre-wrap;line-height:1.65;overflow-wrap:anywhere}.quality-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:0 14px}.drawer-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:18px}
@media(max-width:960px){.generation-metrics,.candidate-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:640px){.generation-metrics,.generation-form-grid,.candidate-grid,.quality-grid{grid-template-columns:1fr}.generation-form-grid .mother-field{grid-column:auto}.generation-task-card header{flex-direction:column}.task-meta{align-items:flex-start}.candidate-card{min-height:auto}}
</style>
