package com.neu.riketiku.zhishikapian;
import com.neu.riketiku.aishengcheng.AiQuestionGenerationService;import com.neu.riketiku.renzheng.RenZhengYeWuYiChang;import com.neu.riketiku.xueshenglianxi.ObjectiveAnswerGrader;import java.util.List;import java.util.Set;import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import tools.jackson.databind.JsonNode;import tools.jackson.databind.ObjectMapper;
@Service public class KnowledgeCardPracticeService{private static final Set<String>TYPES=Set.of("SINGLE_CHOICE","MULTIPLE_CHOICE","FILL_BLANK");private final JdbcTemplate jdbc;private final AiQuestionGenerationService generator;private final ObjectiveAnswerGrader grader;private final ObjectMapper mapper=new ObjectMapper();public KnowledgeCardPracticeService(JdbcTemplate jdbc,AiQuestionGenerationService generator,ObjectiveAnswerGrader grader){this.jdbc=jdbc;this.generator=generator;this.grader=grader;}
public List<KnowledgeCardPracticeDtos.Exercise>generate(long user,long card,KnowledgeCardPracticeDtos.Generate request){if(!TYPES.contains(request.questionType()))throw error("KNOWLEDGE_CARD_PRACTICE_TYPE_INVALID","卡片练习仅支持单选、多选和填空",HttpStatus.BAD_REQUEST);long student=student(user);var task=generator.generateFromKnowledgeCard(user,card,request.questionType(),request.difficulty(),request.variationMode(),request.count(),(taskId,questions)->{for(long question:questions)jdbc.update("INSERT INTO zhi_shi_ka_pian_lian_xi_shi_li(gao_pin_kao_dian_id,xue_sheng_id,ai_sheng_cheng_ren_wu_id,ti_mu_id) VALUES (?,?,?,?)",card,student,taskId,question);});return byTask(user,task.id());}
@Transactional public KnowledgeCardPracticeDtos.Exercise answer(long user,long id,JsonNode submitted){Row row=row(user,id,true);if(!"READY".equals(row.status()))throw error("KNOWLEDGE_CARD_PRACTICE_ALREADY_ANSWERED","本题已经作答",HttpStatus.CONFLICT);boolean correct=grader.grade(row.type(),row.correctAnswer(),optionsJson(row.questionId()),submitted);jdbc.update("UPDATE zhi_shi_ka_pian_lian_xi_shi_li SET xue_sheng_da_an=?,shi_fou_zheng_que=?,zhuang_tai='ANSWERED',zuo_da_shi_jian=CURRENT_TIMESTAMP(3) WHERE id=?",submitted.toString(),correct,id);return detail(user,id);}
@Transactional public KnowledgeCardPracticeDtos.Exercise submit(long user,long id){Row row=row(user,id,true);if("READY".equals(row.status()))throw error("KNOWLEDGE_CARD_PRACTICE_ANSWER_REQUIRED","请先完成作答",HttpStatus.CONFLICT);if("ANSWERED".equals(row.status()))jdbc.update("UPDATE zhi_shi_ka_pian_lian_xi_shi_li SET zhuang_tai='SUBMITTED_REVIEW',ti_jiao_shi_jian=CURRENT_TIMESTAMP(3) WHERE id=?",id);return detail(user,id);}
@Transactional(readOnly=true)public KnowledgeCardPracticeDtos.Exercise detail(long user,long id){return toDto(row(user,id,false));}@Transactional(readOnly=true)public List<KnowledgeCardPracticeDtos.Exercise>byTask(long user,long task){return jdbc.query("SELECT i.id FROM zhi_shi_ka_pian_lian_xi_shi_li i JOIN xue_sheng_dang_an s ON s.id=i.xue_sheng_id WHERE i.ai_sheng_cheng_ren_wu_id=? AND s.yong_hu_id=? ORDER BY i.id",(rs,n)->detail(user,rs.getLong(1)),task,user);}
private Row row(long user,long id,boolean lock){return jdbc.query("""
SELECT i.id,i.gao_pin_kao_dian_id,i.ai_sheng_cheng_ren_wu_id,i.ti_mu_id,i.zhuang_tai,q.ti_mu_lei_xing,q.ti_gan,q.nan_du,CAST(i.xue_sheng_da_an AS CHAR),i.shi_fou_zheng_que,CAST(q.zheng_que_da_an AS CHAR),a.jie_xi_nei_rong,v.bian_shi_zhai_yao
FROM zhi_shi_ka_pian_lian_xi_shi_li i JOIN xue_sheng_dang_an s ON s.id=i.xue_sheng_id JOIN ti_mu q ON q.id=i.ti_mu_id JOIN ti_mu_jie_xi a ON a.ti_mu_id=q.id AND a.jie_xi_lei_xing='STANDARD' AND a.yi_shan_chu=0 JOIN ai_hou_xuan_ti_zhi_liang_ping_jia v ON v.ti_mu_id=q.id WHERE i.id=? AND s.yong_hu_id=?
"""+(lock?" FOR UPDATE":""),(rs,n)->new Row(rs.getLong(1),rs.getLong(2),rs.getLong(3),rs.getLong(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getInt(8),rs.getString(9),rs.getObject(10,Boolean.class),rs.getString(11),rs.getString(12),rs.getString(13)),id,user).stream().findFirst().orElseThrow(()->error("KNOWLEDGE_CARD_PRACTICE_NOT_FOUND","卡片练习不存在",HttpStatus.NOT_FOUND));}
private KnowledgeCardPracticeDtos.Exercise toDto(Row r){boolean answered=!"READY".equals(r.status());return new KnowledgeCardPracticeDtos.Exercise(r.id(),r.cardId(),r.taskId(),r.questionId(),r.status(),r.type(),r.stem(),r.difficulty(),answerSlots(r.type(),r.correctAnswer()),options(r.questionId()),answered&&r.studentAnswer()!=null?mapper.readTree(r.studentAnswer()):null,answered?r.correct():null,answered?mapper.readTree(r.correctAnswer()):null,answered?r.analysis():null,r.summary());}
private int answerSlots(String type,String answerJson){if(!"FILL_BLANK".equals(type))return 1;JsonNode answer=mapper.readTree(answerJson);return answer.path("blanks").isArray()?Math.max(1,answer.path("blanks").size()):1;}
private List<KnowledgeCardPracticeDtos.Option>options(long question){return jdbc.query("SELECT xuan_xiang_biao_shi,xuan_xiang_nei_rong FROM ti_mu_xuan_xiang WHERE ti_mu_id=? AND yi_shan_chu=0 ORDER BY pai_xu",(rs,n)->new KnowledgeCardPracticeDtos.Option(rs.getString(1),rs.getString(2)),question);}private String optionsJson(long question){try{return mapper.writeValueAsString(options(question));}catch(Exception e){throw new IllegalStateException(e);}}private long student(long user){return jdbc.query("SELECT id FROM xue_sheng_dang_an WHERE yong_hu_id=? AND zhuang_tai='ACTIVE' AND yi_shan_chu=0",(rs,n)->rs.getLong(1),user).stream().findFirst().orElseThrow(()->error("STUDENT_PROFILE_REQUIRED","学生档案不可用",HttpStatus.FORBIDDEN));}private RenZhengYeWuYiChang error(String code,String message,HttpStatus status){return new RenZhengYeWuYiChang(code,message,status);}private record Row(long id,long cardId,long taskId,long questionId,String status,String type,String stem,int difficulty,String studentAnswer,Boolean correct,String correctAnswer,String analysis,String summary){}
}
