CREATE TABLE shi_juan_fa_bu (
    id BIGINT NOT NULL AUTO_INCREMENT,
    shi_juan_id BIGINT NOT NULL,
    ren_ke_guan_xi_id BIGINT NOT NULL,
    ban_ji_id BIGINT NOT NULL,
    ke_mu_id BIGINT NOT NULL,
    fa_bu_jiao_shi_id BIGINT NOT NULL,
    ban_ben_hao INT NOT NULL DEFAULT 1,
    kuai_zhao_ha_xi CHAR(64) NOT NULL,
    fa_bu_shi_jian DATETIME(3) NOT NULL,
    jie_zhi_shi_jian DATETIME(3) NOT NULL,
    zhuang_tai VARCHAR(16) NOT NULL DEFAULT 'PUBLISHED',
    chuang_jian_shi_jian DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY(id),
    UNIQUE KEY uk_shi_juan_fa_bu_version_scope (shi_juan_id, ban_ben_hao, ren_ke_guan_xi_id),
    KEY idx_shi_juan_fa_bu_class_subject (ban_ji_id, ke_mu_id, zhuang_tai, jie_zhi_shi_jian),
    KEY idx_shi_juan_fa_bu_teacher (fa_bu_jiao_shi_id, chuang_jian_shi_jian),
    CONSTRAINT fk_shi_juan_fa_bu_paper FOREIGN KEY(shi_juan_id) REFERENCES shi_juan(id) ON DELETE RESTRICT,
    CONSTRAINT fk_shi_juan_fa_bu_scope FOREIGN KEY(ren_ke_guan_xi_id) REFERENCES ren_ke_guan_xi(id) ON DELETE RESTRICT,
    CONSTRAINT fk_shi_juan_fa_bu_class FOREIGN KEY(ban_ji_id) REFERENCES ban_ji(id) ON DELETE RESTRICT,
    CONSTRAINT fk_shi_juan_fa_bu_subject FOREIGN KEY(ke_mu_id) REFERENCES ke_mu(id) ON DELETE RESTRICT,
    CONSTRAINT fk_shi_juan_fa_bu_teacher FOREIGN KEY(fa_bu_jiao_shi_id) REFERENCES jiao_shi_dang_an(id) ON DELETE RESTRICT,
    CONSTRAINT ck_shi_juan_fa_bu_version CHECK(ban_ben_hao >= 1),
    CONSTRAINT ck_shi_juan_fa_bu_time CHECK(jie_zhi_shi_jian > fa_bu_shi_jian),
    CONSTRAINT ck_shi_juan_fa_bu_status CHECK(zhuang_tai IN ('PUBLISHED','CLOSED','CANCELLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='班级试卷发布与冻结版本';

CREATE TABLE shi_juan_fa_bu_ti_mu (
    id BIGINT NOT NULL AUTO_INCREMENT,
    shi_juan_fa_bu_id BIGINT NOT NULL,
    ti_mu_id BIGINT NOT NULL,
    ti_mu_shun_xu INT NOT NULL,
    fen_zhi DECIMAL(8,2) NOT NULL,
    ti_mu_lei_xing VARCHAR(32) NOT NULL,
    ti_gan_kuai_zhao LONGTEXT NOT NULL,
    xuan_xiang_kuai_zhao JSON NULL,
    zheng_que_da_an_kuai_zhao JSON NOT NULL,
    biao_zhun_jie_xi_kuai_zhao LONGTEXT NOT NULL,
    zhi_shi_dian_kuai_zhao JSON NOT NULL,
    PRIMARY KEY(id),
    UNIQUE KEY uk_shi_juan_fa_bu_ti_mu_order (shi_juan_fa_bu_id, ti_mu_shun_xu),
    UNIQUE KEY uk_shi_juan_fa_bu_ti_mu_question (shi_juan_fa_bu_id, ti_mu_id),
    KEY idx_shi_juan_fa_bu_ti_mu_question (ti_mu_id),
    CONSTRAINT fk_shi_juan_fa_bu_ti_mu_release FOREIGN KEY(shi_juan_fa_bu_id) REFERENCES shi_juan_fa_bu(id) ON DELETE RESTRICT,
    CONSTRAINT fk_shi_juan_fa_bu_ti_mu_question FOREIGN KEY(ti_mu_id) REFERENCES ti_mu(id) ON DELETE RESTRICT,
    CONSTRAINT ck_shi_juan_fa_bu_ti_mu_order CHECK(ti_mu_shun_xu >= 1),
    CONSTRAINT ck_shi_juan_fa_bu_ti_mu_score CHECK(fen_zhi > 0),
    CONSTRAINT ck_shi_juan_fa_bu_ti_mu_type CHECK(ti_mu_lei_xing IN ('SINGLE_CHOICE','MULTIPLE_CHOICE','FILL_BLANK','SUBJECTIVE')),
    CONSTRAINT ck_shi_juan_fa_bu_ti_mu_options CHECK(xuan_xiang_kuai_zhao IS NULL OR JSON_TYPE(xuan_xiang_kuai_zhao)='ARRAY'),
    CONSTRAINT ck_shi_juan_fa_bu_ti_mu_answer CHECK(JSON_TYPE(zheng_que_da_an_kuai_zhao)='OBJECT'),
    CONSTRAINT ck_shi_juan_fa_bu_ti_mu_points CHECK(JSON_TYPE(zhi_shi_dian_kuai_zhao)='ARRAY')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='已发布试卷题目冻结快照';

CREATE TABLE shi_juan_ti_jiao (
    id BIGINT NOT NULL AUTO_INCREMENT,
    shi_juan_fa_bu_id BIGINT NOT NULL,
    xue_sheng_id BIGINT NOT NULL,
    zhuang_tai VARCHAR(16) NOT NULL DEFAULT 'IN_PROGRESS',
    ke_guan_de_fen DECIMAL(10,2) NOT NULL DEFAULT 0,
    ke_guan_zong_fen DECIMAL(10,2) NOT NULL DEFAULT 0,
    kai_shi_shi_jian DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ti_jiao_shi_jian DATETIME(3) NULL,
    geng_xin_shi_jian DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY(id),
    UNIQUE KEY uk_shi_juan_ti_jiao_release_student (shi_juan_fa_bu_id, xue_sheng_id),
    KEY idx_shi_juan_ti_jiao_student (xue_sheng_id, zhuang_tai, geng_xin_shi_jian),
    CONSTRAINT fk_shi_juan_ti_jiao_release FOREIGN KEY(shi_juan_fa_bu_id) REFERENCES shi_juan_fa_bu(id) ON DELETE RESTRICT,
    CONSTRAINT fk_shi_juan_ti_jiao_student FOREIGN KEY(xue_sheng_id) REFERENCES xue_sheng_dang_an(id) ON DELETE RESTRICT,
    CONSTRAINT ck_shi_juan_ti_jiao_status CHECK(zhuang_tai IN ('IN_PROGRESS','SUBMITTED')),
    CONSTRAINT ck_shi_juan_ti_jiao_score CHECK(ke_guan_de_fen >= 0 AND ke_guan_zong_fen >= ke_guan_de_fen),
    CONSTRAINT ck_shi_juan_ti_jiao_time CHECK(ti_jiao_shi_jian IS NULL OR ti_jiao_shi_jian >= kai_shi_shi_jian)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='学生试卷提交事实';

CREATE TABLE shi_juan_xue_sheng_da_ti (
    id BIGINT NOT NULL AUTO_INCREMENT,
    shi_juan_ti_jiao_id BIGINT NOT NULL,
    shi_juan_fa_bu_ti_mu_id BIGINT NOT NULL,
    xue_sheng_da_an JSON NULL,
    shi_fou_zheng_que TINYINT(1) NULL,
    de_fen DECIMAL(8,2) NULL,
    zhuang_tai VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    bao_cun_shi_jian DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY(id),
    UNIQUE KEY uk_shi_juan_xue_sheng_da_ti_submission_item (shi_juan_ti_jiao_id, shi_juan_fa_bu_ti_mu_id),
    KEY idx_shi_juan_xue_sheng_da_ti_item (shi_juan_fa_bu_ti_mu_id),
    CONSTRAINT fk_shi_juan_xue_sheng_da_ti_submission FOREIGN KEY(shi_juan_ti_jiao_id) REFERENCES shi_juan_ti_jiao(id) ON DELETE RESTRICT,
    CONSTRAINT fk_shi_juan_xue_sheng_da_ti_item FOREIGN KEY(shi_juan_fa_bu_ti_mu_id) REFERENCES shi_juan_fa_bu_ti_mu(id) ON DELETE RESTRICT,
    CONSTRAINT ck_shi_juan_xue_sheng_da_ti_correct CHECK(shi_fou_zheng_que IS NULL OR shi_fou_zheng_que IN (0,1)),
    CONSTRAINT ck_shi_juan_xue_sheng_da_ti_score CHECK(de_fen IS NULL OR de_fen >= 0),
    CONSTRAINT ck_shi_juan_xue_sheng_da_ti_status CHECK(zhuang_tai IN ('DRAFT','GRADED','SUBJECTIVE_PENDING'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='学生试卷答题与确定性判分';
