CREATE TABLE zhi_shi_ka_pian_lian_xi_shi_li (
    id BIGINT NOT NULL AUTO_INCREMENT,
    gao_pin_kao_dian_id BIGINT NOT NULL,
    xue_sheng_id BIGINT NOT NULL,
    ai_sheng_cheng_ren_wu_id BIGINT NOT NULL,
    ti_mu_id BIGINT NOT NULL,
    xue_sheng_da_an JSON NULL,
    shi_fou_zheng_que TINYINT(1) NULL,
    zhuang_tai VARCHAR(24) NOT NULL DEFAULT 'READY',
    chuang_jian_shi_jian DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    zuo_da_shi_jian DATETIME(3) NULL,
    ti_jiao_shi_jian DATETIME(3) NULL,
    PRIMARY KEY(id),
    UNIQUE KEY uk_card_practice_task_question_student(ai_sheng_cheng_ren_wu_id,ti_mu_id,xue_sheng_id),
    KEY idx_card_practice_student(xue_sheng_id,zhuang_tai,chuang_jian_shi_jian),
    KEY idx_card_practice_card(gao_pin_kao_dian_id,chuang_jian_shi_jian),
    CONSTRAINT fk_card_practice_card FOREIGN KEY(gao_pin_kao_dian_id) REFERENCES gao_pin_kao_dian(id) ON DELETE RESTRICT,
    CONSTRAINT fk_card_practice_student FOREIGN KEY(xue_sheng_id) REFERENCES xue_sheng_dang_an(id) ON DELETE RESTRICT,
    CONSTRAINT fk_card_practice_task FOREIGN KEY(ai_sheng_cheng_ren_wu_id) REFERENCES ai_sheng_cheng_ren_wu(id) ON DELETE RESTRICT,
    CONSTRAINT fk_card_practice_question FOREIGN KEY(ti_mu_id) REFERENCES ti_mu(id) ON DELETE RESTRICT,
    CONSTRAINT ck_card_practice_correct CHECK(shi_fou_zheng_que IS NULL OR shi_fou_zheng_que IN(0,1)),
    CONSTRAINT ck_card_practice_state CHECK(zhuang_tai IN('READY','ANSWERED','SUBMITTED_REVIEW')),
    CONSTRAINT ck_card_practice_answer_state CHECK((zhuang_tai='READY' AND xue_sheng_da_an IS NULL AND shi_fou_zheng_que IS NULL) OR (zhuang_tai IN('ANSWERED','SUBMITTED_REVIEW') AND xue_sheng_da_an IS NOT NULL AND shi_fou_zheng_que IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='知识卡片临时练习、确定性判分与待审核提交事实';
