CREATE TABLE gao_pin_kao_dian (
    id BIGINT NOT NULL AUTO_INCREMENT,
    ren_ke_guan_xi_id BIGINT NOT NULL COMMENT '所属三元任课关系',
    zhi_shi_dian_id BIGINT NOT NULL COMMENT '所属科目知识点',
    biao_ti VARCHAR(200) NOT NULL,
    nei_rong TEXT NOT NULL,
    ji_yi_kou_jue VARCHAR(500) NULL,
    chang_jian_wu_qu TEXT NULL,
    pai_xu INT NOT NULL DEFAULT 0,
    zhuang_tai VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    chuang_jian_shi_jian DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    geng_xin_shi_jian DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    yi_shan_chu TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_gao_pin_kao_dian_scope_status (ren_ke_guan_xi_id, zhuang_tai, yi_shan_chu, pai_xu, id),
    KEY idx_gao_pin_kao_dian_knowledge (zhi_shi_dian_id),
    CONSTRAINT fk_gao_pin_kao_dian_scope FOREIGN KEY (ren_ke_guan_xi_id) REFERENCES ren_ke_guan_xi (id) ON DELETE RESTRICT,
    CONSTRAINT fk_gao_pin_kao_dian_knowledge FOREIGN KEY (zhi_shi_dian_id) REFERENCES zhi_shi_dian (id) ON DELETE RESTRICT,
    CONSTRAINT ck_gao_pin_kao_dian_title CHECK (CHAR_LENGTH(TRIM(biao_ti)) BETWEEN 1 AND 200),
    CONSTRAINT ck_gao_pin_kao_dian_content CHECK (CHAR_LENGTH(TRIM(nei_rong)) > 0),
    CONSTRAINT ck_gao_pin_kao_dian_order CHECK (pai_xu >= 0),
    CONSTRAINT ck_gao_pin_kao_dian_status CHECK (zhuang_tai IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT ck_gao_pin_kao_dian_deleted CHECK (yi_shan_chu IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='教师维护的班级学科高频考点';
